#!/usr/bin/env perl

use strict;
use warnings;

use Test::More qw(no_plan); # for the is() and isnt() functions
use IPC::Run qw(run);
use FindBin;
my $testee = "$FindBin::Bin/rk";

sub get_meta() {
    my ($file) = @_;

    my $dump=`getfattr -d '$file'`;

    open my $fh, '<', \$dump;

    my %fields;
    while (<$fh>) {
        next unless m/^[\s]*user.rk.(md5|htime|state|vtime)="(.*)"[\s]*$/;
        $fields{$1} = $2;
    }

    return %fields;
}

sub invoke {
	my ($mode, @files) = (@_);
	run [ $testee, "-$mode", @files ], ">", \my $out or die;
	return $out;
}

sub clobber_file {
	my ($file, $content) = @_;
    system("echo -n '$content' > '$file'");	
}

################################################################################
# Test constants

my $v1 = 'abcdefghijklmnopqrstuvwxyz';
my $v2 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
my $v3 = '0123456789';

my $h1 = 'c3fcd3d76192e4007dfb496cca67e13b';
my $h2 = '437bba8e0bf58337674f4539e75186ac';
my $h3 = '781e5e245d69b566979b86e28d23f2c7';

my $fs = shift;
my $lt1 = "1 with space.testfile";
my $f1 = "$fs/$lt1";
my $f2 = "$fs/2 with space.testfile";

################################################################################

# TODO:
# -l    Default: Print some status line
# -v    Verify metadata where it exists
# -a    Combination -n & -v
# -x    Delete all metadata. - THIS NEEDS RETESTING WITH ALL 4 KEYS!
# -e    (export)

&test_nx();
&test_nv();
&test_a ();
&test_e ();
&test_l ();

exit 0;

################################################################################

sub test_nx() {
	my %meta;

	&clobber_file($f1, $v1);

	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	&is(&invoke('n', ($f1)), "? $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&is(length($meta{htime}),19); # TODO FORMAT CHECK

	my $htime = $meta{htime};

	&is(&invoke('n', ($f1)), "? $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&ok($meta{htime} eq $htime); # TODO FORMAT CHECK

	&clobber_file($f1, $v2);

	sleep(1);
	&is(&invoke('x', ($f1)), "  $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

    unlink $f1;
}

sub test_nv() {
	my %meta;

	&clobber_file($f1, $v1);

	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	&is(&invoke('v', ($f1)), "  $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	&is(&invoke('n', ($f1)), "? $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&is(length($meta{htime}),19); # TODO FORMAT CHECK

	my $htime = $meta{htime};

	sleep(1);
	&is(&invoke('v', ($f1)), "V $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,4);
	&is($meta{md5},$h1);
	&is($meta{htime},$htime); # TODO FORMAT CHECK
	&is($meta{state},'V');
	&ok($meta{vtime} gt $meta{htime}); # TODO FORMAT CHECK

	my $last_vtime = $meta{vtime};

	&clobber_file($f1, $v2);

	sleep(1);
	&is(&invoke('v', ($f1)), "X $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,4);
	&is($meta{md5},$h1);
	&is($meta{htime},$htime); # TODO FORMAT CHECK
	&is($meta{state},'X');
	&ok($meta{vtime} eq $last_vtime); # TODO FORMAT CHECK

    unlink $f1;
}

sub test_a() {
	my %meta;

	&clobber_file($f1, $v1);

	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	&is(&invoke('a', ($f1)), "? $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&is(length($meta{htime}),19); # TODO FORMAT CHECK

	my $htime = $meta{htime};

	&clobber_file($f1, $v3);
	&clobber_file($f2, $v2);

	%meta = &get_meta($f2);
	&is(scalar keys %meta,0);

	sleep(1);
	&is(
		&invoke('a', ($f1, $f2)),
		"X $f1\n? $f2\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,3);
	&is($meta{md5},$h1);
	&is($meta{htime},$htime); # TODO FORMAT CHECK
	&is($meta{state},'X');
	%meta = &get_meta($f2);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h2);
	&ok($meta{htime} gt $htime); # TODO FORMAT CHECK

    unlink $f1, $f2;
}

sub test_e {
	my %meta;

	&clobber_file($f1, $v1);

	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	&is(&invoke('e', ($f1)), "        26  ????????????????????????????????  $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	&is(&invoke('a', ($f1)), "? $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&is(length($meta{htime}),19); # TODO FORMAT CHECK

	&is(&invoke('e', ($f1)), "        26  $h1  $f1\n");
	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&is(length($meta{htime}),19); # TODO FORMAT CHECK

    unlink $f1;
}

sub test_l {
	my %meta;

	&clobber_file($f1, $v1);

	%meta = &get_meta($f1);
	&is(scalar keys %meta,0);

	symlink($lt1, $f2) or die "Couldn't create symlink!";

	%meta = &get_meta($f2);
	&is(scalar keys %meta,0);

	&is(&invoke('n', ($f2)), "? $f2\n");
	%meta = &get_meta($f2);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&is(length($meta{htime}),19); # TODO FORMAT CHECK

	my $htime = $meta{htime};

	%meta = &get_meta($f1);
	&is(scalar keys %meta,2);
	&is($meta{md5},$h1);
	&ok($meta{htime} eq $htime); # TODO FORMAT CHECK

	unlink $f1,$f2;
}
